Update create_domain

diff --git a/create_domain b/create_domain
--- a/create_domain
+++ b/create_domain
@@ -52,129 +52,129 @@ systemctl enable httpd
 systemctl restart httpd
 
 if [ "$action" == 'create' ]
-	then
-		### check if domain already exists
-		if [ -e $sitesAvailabledomain ]; then
-			echo -e $"This domain already exists.\nPlease Try Another one"
+then
+	### check if domain already exists
+	if [ -e $sitesAvailabledomain ]; then
+		echo -e $"This domain already exists.\nPlease Try Another one"
+		exit;
+	fi
+
+	### check if directory exists or not
+	if ! [ -d $rootDir ]; then
+		### create the directory
+		mkdir $rootDir
+		### give permission to root dir
+		chmod 755 $rootDir
+		### write test file in the new domain dir
+		if ! echo $"Hello Welcome to http://$domain"  > $rootDir/index.html
+		then
+			echo $"ERROR: Not able to write in file $rootDir/index.html. Please check permissions"
 			exit;
+		else
+			echo $"Added content to $rootDir/index.html"
 		fi
+	fi
 
-		### check if directory exists or not
-		if ! [ -d $rootDir ]; then
-			### create the directory
-			mkdir $rootDir
-			### give permission to root dir
-			chmod 755 $rootDir
-			### write test file in the new domain dir
-			if ! echo $"Hello Welcome to http://$domain"  > $rootDir/index.html
-			then
-				echo $"ERROR: Not able to write in file $rootDir/index.html. Please check permissions"
-				exit;
-			else
-				echo $"Added content to $rootDir/index.html"
-			fi
-		fi
-		
-		grep -qxF 'IncludeOptional sites-enabled/*.conf' $confFile || echo 'IncludeOptional sites-enabled/*.conf' >> $confFile
-		
-		if [ ! -f $sitesEnableDefault ]; then
-			if ! echo "
-				<VirtualHost *:80>
-					DocumentRoot /var/www/html
-				</VirtualHost>" > $sitesEnableDefault
-			then
-				echo -e $"There is an ERROR creating default conf file"
-				exit;
-			fi
-		fi
+	grep -qxF 'IncludeOptional sites-enabled/*.conf' $confFile || echo 'IncludeOptional sites-enabled/*.conf' >> $confFile
 
-		### create virtual host rules file
+	if [ ! -f $sitesEnableDefault ]; then
 		if ! echo "
-		<VirtualHost *:80>
-			ServerAdmin $email
-			ServerName $domain
-			ServerAlias $domain
-			DocumentRoot $rootDir
-			<Directory />
-				AllowOverride All
-			</Directory>
-			<Directory $rootDir>
-				Options Indexes FollowSymLinks MultiViews
-				AllowOverride all
-				Require all granted
-			</Directory>
-			ErrorLog /var/log/httpd/$domain-error.log
-			LogLevel error
-			CustomLog /var/log/httpd/$domain-access.log combined
-		</VirtualHost>" > $sitesAvailabledomain
+			<VirtualHost *:80>
+				DocumentRoot /var/www/html
+			</VirtualHost>" > $sitesEnableDefault
 		then
-			echo -e $"There is an ERROR creating $domain file"
+			echo -e $"There is an ERROR creating default conf file"
 			exit;
-		else
-			echo -e $"\nNew Virtual Host Created\n"
 		fi
+	fi
 
-		### Add domain in /etc/hosts
-		if ! echo "127.0.0.1	$domain" >> /etc/hosts
-		then
-			echo $"ERROR: Not able to write in /etc/hosts"
-			exit;
-		else
-			echo -e $"Host added to /etc/hosts file \n"
-		fi
-
-		if [ "$owner" == "" ]; then
-			chown -R $(whoami):$(whoami) $rootDir
-		else
-			chown -R $owner:$owner $rootDir
-		fi
-
-		### enable website
-		cp $sitesAvailabledomain $sitesEnable/$domain.conf
-
-		### restart Apache
-        	systemctl restart httpd
-
-		### show the finished message
-		echo -e $"Complete! \nYou now have a new Virtual Host \nYour new host is: http://$domain \nAnd its located at $rootDir"
+	### create virtual host rules file
+	if ! echo "
+	<VirtualHost *:80>
+		ServerAdmin $email
+		ServerName $domain
+		ServerAlias $domain
+		DocumentRoot $rootDir
+		<Directory />
+			AllowOverride All
+		</Directory>
+		<Directory $rootDir>
+			Options Indexes FollowSymLinks MultiViews
+			AllowOverride all
+			Require all granted
+		</Directory>
+		ErrorLog /var/log/httpd/$domain-error.log
+		LogLevel error
+		CustomLog /var/log/httpd/$domain-access.log combined
+	</VirtualHost>" > $sitesAvailabledomain
+	then
+		echo -e $"There is an ERROR creating $domain file"
 		exit;
 	else
-		### check whether domain already exists
-		if ! [ -e $sitesAvailabledomain ]; then
-			echo -e $"This domain does not exist.\nPlease try another one"
-			exit;
+		echo -e $"\nNew Virtual Host Created\n"
+	fi
+
+	### Add domain in /etc/hosts
+	if ! echo "127.0.0.1	$domain" >> /etc/hosts
+	then
+		echo $"ERROR: Not able to write in /etc/hosts"
+		exit;
+	else
+		echo -e $"Host added to /etc/hosts file \n"
+	fi
+
+	if [ "$owner" == "" ]; then
+		chown -R $(whoami):$(whoami) $rootDir
+	else
+		chown -R $owner:$owner $rootDir
+	fi
+
+	### enable website
+	cp $sitesAvailabledomain $sitesEnable/$domain.conf
+
+	### restart Apache
+	systemctl restart httpd
+
+	### show the finished message
+	echo -e $"Complete! \nYou now have a new Virtual Host \nYour new host is: http://$domain \nAnd its located at $rootDir"
+	exit;
+else
+	### check whether domain already exists
+	if ! [ -e $sitesAvailabledomain ]; then
+		echo -e $"This domain does not exist.\nPlease try another one"
+		exit;
+	else
+		### Delete domain in /etc/hosts
+		newhost=${domain//./\\.}
+		sed -i "/$newhost/d" /etc/hosts
+
+		### disable website
+		rm -f $sitesEnable/$domain.conf
+
+		### restart Apache
+		systemctl restart httpd
+
+		### Delete virtual host rules files
+		rm $sitesAvailabledomain
+	fi
+
+	### check if directory exists or not
+	if [ -d $rootDir ]; then
+		echo -e $"Delete host root directory ? (y/n)"
+		read deldir
+
+		if [ "$deldir" == 'y' -o "$deldir" == 'Y' ]; then
+			### Delete the directory
+			rm -rf $rootDir
+			echo -e $"Directory deleted"
 		else
-			### Delete domain in /etc/hosts
-			newhost=${domain//./\\.}
-			sed -i "/$newhost/d" /etc/hosts
-
-			### disable website
-			rm -f $sitesEnable/$domain.conf
-
-			### restart Apache
-			systemctl restart httpd
-
-			### Delete virtual host rules files
-			rm $sitesAvailabledomain
+			echo -e $"Host directory conserved"
 		fi
+	else
+		echo -e $"Host directory not found. Ignored"
+	fi
 
-		### check if directory exists or not
-		if [ -d $rootDir ]; then
-			echo -e $"Delete host root directory ? (y/n)"
-			read deldir
-
-			if [ "$deldir" == 'y' -o "$deldir" == 'Y' ]; then
-				### Delete the directory
-				rm -rf $rootDir
-				echo -e $"Directory deleted"
-			else
-				echo -e $"Host directory conserved"
-			fi
-		else
-			echo -e $"Host directory not found. Ignored"
-		fi
-
-		### show the finished message
-		echo -e $"Complete!\nYou just removed Virtual Host $domain"
-		exit 0;
+	### show the finished message
+	echo -e $"Complete!\nYou just removed Virtual Host $domain"
+	exit 0;
 fi
